### ISSUE TITLE
Combat ready missing JS file

### ISSUE THREAD

**Issue by ZeroXNoxus** [Teshynil/combatready#14]
**Describe the bug**
I re-installed Combat Ready! (CR!) and I've noticed that the turn timers does not start when I start an encounter. I've noticed that after activation I can't find the CR! settings either, and after digging some more I've seen that the src files of CR! only include the css in my current configuration. See the screenshots below for further information (yes, of course I have activated the modules). I've also run CR! without the Themes module, but there wasn't any difference.

Is there something that I'm missing? When looking in the server files I can see the .js file sitting there, but it seems like it isn't getting executed.

**To Reproduce**
1. Install CR!
2. Activate CR!

**Expected behavior**
Well, of course it should work when running in a clean environment?

**Screenshots**
![image](https://user-images.githubusercontent.com/29397572/141657312-803eb426-986f-4788-9d3c-9df1096e4e3f.png)
![image](https://user-images.githubusercontent.com/29397572/141657323-6746c596-3b13-43be-a2a8-22e85c0b657a.png)
![image](https://user-images.githubusercontent.com/29397572/141657339-5e250007-4aa5-41ae-9c51-9fee853ad565.png)

**Browser:**
 - Chrome v 95.0.4638.69

**Foundry Version:** 
- FoundryVTT 0.8.9

**System:** 
- DnD 5th Edition v 1.5.3

**Additional context**
-

**Comment by Teshynil** [comment]
@ZeroXNoxus I have checked, and can not reproduce the bug, there is an error in the console when loading foundry?
please try with ctrl+shift+R in order to load all files from zero and not a cache copy

**Comment by ZeroXNoxus** [comment]
@Teshynil I've reloaded the website multiple times without cache, sadly to no avail. Here is my console with only the error logs:

![Screenshot 2021-11-18 160345](https://user-images.githubusercontent.com/29397572/142440951-027a8dfb-dc09-47bb-a597-b963974bcf7a.jpg)

We run foundry on a dedicated server, maybe we need to restart the server for the module to initialize? 
I've seen, however, that the supposed .js file in the module is called a .ts file. Maybe this is the problem? The module.json may not be able to fetch the correct file?

![image](https://user-images.githubusercontent.com/29397572/142441412-6b5f0b89-3d60-4f16-a57c-9620b8750a68.png)

**Comment by Teshynil** [comment]
@ZeroXNoxus If you use the in-game installer it download the compile code, this repository contain the code for compilation, maybe what you need to do is delete the folder inside the foundryvvt data folder if you would like i can provide assistance via discord Teshynil#8564

**Comment by Teshynil** [comment]
@ZeroXNoxus It should be working in 3.2.1
