### ISSUE TITLE
[question] V9 compatibility

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Teshynil/combatready#15]
Hello, my group loves this module and doesn't want to miss it, so before updating to Foundry V9 I wanted to ask: Is Combat Ready still working there? Or is any update planned? Thank you!

**Comment by Teshynil** [comment]
Currently the module its expected to work in V9 Also I'm working in an proper v9 update.

**Comment by KnoepfchenFulla** [comment]
Awesome, thanks!

**Comment by Teshynil** [comment]
Added in 4.0.0
