### ISSUE TITLE
Timer seems to no longer be counting down with recent Foundry updates

### ISSUE THREAD

**Issue by TombstoneTT** [Teshynil/combatready#16]
As said in the title: I tried disabling everything except Combat Ready and its dependencies, but the timer bar no longer fills.

**Comment by Teshynil** [comment]
Hi, Which build are you currently and could you share your settings please

**Comment by TombstoneTT** [comment]
4.0.0 of Combat Ready, Foundry V9 and Build 249, and basically all default settings for Combat Ready.

**Comment by Teshynil** [comment]
Weird, could you share a screenshot or video, i recreate a world but it works as intended, please check the console in case there are errors showing up

**Comment by TombstoneTT** [comment]
Was recording a video and it just inexplicably started working again. Maybe it's because I changed the time value back and forth? I have no clue. Sorry for the wasted time, I have no idea what actually caused it. There was no errors in the console either.

**Comment by Teshynil** [comment]
No problem, if you experience the error don't hesitate to contact me here or via discord Teshynil#8564
