### ISSUE TITLE
Theming - Create a Template for custom themes

### ISSUE THREAD

**Issue by Gensokian** [Teshynil/combatready#17]
I personally love the ability to create themes, but right now I was not able to reverse engineer the default theme enough to completely understand where to put my code for the "Your turn / Next up / New Round" animations.

*by the by, what is the default "new round" animation? I couldn't find any animation for that when testing the animation. 🤔 I might just be blind though :)*

**Comment by Teshynil** [comment]
Hi @Gensokian, currently i am busy with work so i could not implement the template for custom themes but i create this repo [combatreadythemes](https://github.com/Teshynil/combatreadythemes) that maybe with help you in create a theme.
The logic is the same for timers and animations the only thing you need to do is create a class and implement the methods form the base class.
For the new round animation, in the base theme there isn't a New Round Animation, but you could check [/src/module/themes.ts](https://github.com/Teshynil/combatready/blob/master/src/module/themes.ts) the class NativeAnimationTheme follows the same logic that any custom theme should follow

**Comment by Teshynil** [comment]
Also i didn't have any inspiration to create animation themes or timers so i leave the themes repository on hold
