### ISSUE TITLE
Seems to tell players it's their turn when it's not their turn.

### ISSUE THREAD

**Issue by geoidesic** [Teshynil/combatready#18]
Like when I start the combat... suddenly it's EVERYBODY's turn :)

![IMG_6660](https://user-images.githubusercontent.com/4637995/181936437-6cbcc3cc-9177-4802-9d0c-68efbdb0de39.jpg)

You can see top left and bottom right where I'm logged in as two different players.

Pity because otherwise this would be a really useful module :*(

Foundry v0.9

combatready  4.1.1

Tested with no other modules installed.

**Comment by Teshynil** [comment]
Hi @geoidesic, quick question the token which currently is owned by the two players in the permissions view or assigned as limited or observer?

**Comment by geoidesic** [comment]
![Screenshot 2022-07-31 at 10 10 44](https://user-images.githubusercontent.com/4637995/182019265-e65162cc-cf11-43eb-be7e-c04d7bbbb3c4.png)
You're right, it's a permissions thing. If I make sure the tokens have only one owner, it works.

**Comment by Teshynil** [comment]
Hi @geoidesic, mayube would be of interest checking #19, if you have any suggestion for the behaviour
