### ISSUE TITLE
Cannot access 'gsap' before initialization

### ISSUE THREAD

**Issue by CaosFR** [Teshynil/combatready#20]
Hi,

Thanks for your work. I have this problem on combatready when I launch my world : 

```
Uncaught (in promise) ReferenceError: Cannot access 'gsap' before initialization
[Detected 1 package: combatready]
    at NativeAnimation.cleanAnimations (animations.js:266:21)
    at CombatReady.toggleCheck (combatReady.js:346:30)
    at combatready.js:76:17
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5567:11)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)
```

On combat some people have combat ready on and other is off. It's random.
I'm on the last version of foundry v9 and dnd5e. My game is in french.

**Comment by Teshynil** [comment]
Hi @CaosFR, where are you running foundry? hosting, vps, local?
also if you are running with a custom domain it is running at the root of the custom domain or else
example:
myfoundryvttgame.com/game or myfoundryvttgame.com/somethingelse/game

**Comment by CaosFR** [comment]
Thanks for your very quick reply. It's a local hosting. I have a local domain like https://xxx.yyyyy.zz/game

My problem is very random , it's more like a random.

**Comment by Teshynil** [comment]
What modules are active?

**Comment by Teshynil** [comment]
Also i'm available in discord Teshynil#0001

**Comment by CaosFR** [comment]
Active Modules:
----------
Active Token Effects v;
Ambient Doors v;
Autocomplete Inline Properties v;
Autocomplete Whisper v;
Automated Animations v;
Automated Evocations - Companion Manager Variant v;
Auto-Rotate v;
Babele v;
Bar Brawl v;
Cleaner sheet title bar v;
CodeMirror vfvtt5;
Combat Ready! v;
Combat Utility Belt v;
Compendium Folders v;
Custom CSS v;
Day Night Cycle v;
DF Chat Enhancements v;
DFreds Droppables v;
DFreds Effects Panel v;
DFreds Pocket Change v;
Dice So Nice! v;
Drag Ruler v;
Dynamic effects using Active Effects v;
Easy Target v;
Enhanced Terrain Layer v;
Forien's Quest Log v;
fr-FR - DND5 System v;
FR - Traduction du core v;
FXMaster v;
GM Notes v;
GM Screen v;
Health Estimate v;
Hey, listen! - Chat Notifications v;
Hey, Wait! v;
Illandril's Chat Enhancements v;
Illandril's Hotbar Uses v;
Jack Kerouac's Animated Spell Effects v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
Jinker's Animated Art Pack v;
Keyboard Layout v;
Lazy Money v;
Let's Trade 5e v;
lib - Color Settings v;
Library: Chat Commands v;
libWrapper v.0;
LiveKit AVClient v;
LootsheetNPC5e v;
Midi QOL v;
Minimal UI v;
Module Sets - Dual Track GMing, baby v;
Mon Compendium Partage v;
Monk's Hotbar Expansion v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Multiattack 5e v;
Perfect Vision v;
Permission Viewer v;
Pin Cushion v;
Pings v;
Polyglot v;
PopOut! v;
Popout Resizer v;
Rarity Colors v;
Rest Recovery for 5E v;
Sequencer v;
Settings Extender v;
Simple Calendar v;
Simple Dice Roller v;
socketlib v;
Stream View v;
Terrain Ruler v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token Action HUD v;
Token Info Icons v;
Token Magic FX v;
Token Magic FX - Automatic Wounds v;
Torch v;
Warp Gate v;
Weather Control v;
Whisper Box v;
Wild Magic Surge 5e v;

Inactive Modules:
----------
Advanced Macros v;
Changelogs & Conflicts v;
Compendium Browser v;
DF Architect v;
DF Curvy Walls v;
DFreds Convenient Effects v;
DF Settings Clarity v;
Find the culprit v;
Forien's Copy Environment v;
libCaptions v;
Library: DF Module Buttons v;
Maestro v;
Midi SRD v;
Module Compatibility Checker v;
Plantes _5_30PO v;
Plutonium v;
Universal Battlemap Importer v;

**Comment by CaosFR** [comment]
Thanks for your help. English is not my natale langage so I prefer to stay on github. Maybe this post will help other peoples.

Of course I have try whitout any module, it's work. But with my modules it's work to or not. It's random, si I dont know witch module is incompatible.

**Comment by Teshynil** [comment]
Don't worry, i am going to start an investigation and in a few days i will reply to you

**Comment by CaosFR** [comment]
Hi, I will check that, witch log do you want "acces.log" from my proxy ?

**Comment by Teshynil** [comment]
The console log from a player or you when it doesn't work

**Comment by CaosFR** [comment]
Soon I have reproduce the erreor , I will post it here.

**Comment by CaosFR** [comment]
I'm sorry I cannot reproduce the error, for soe reason all it's work now.

**Comment by Teshynil** [comment]
@CaosFR I will be on the lookout for this problem

**Comment by CaosFR** [comment]
Thank you for your great seriousness
