### ISSUE TITLE
No alerts in v10 build 286 D&D 5e

### ISSUE THREAD

**Issue by Rouros** [Teshynil/combatready#21]
On a fresh world with only this module installed I see the timer bar at the bottom, and hear the new round whoosh, but no alerts are given for next player or its your turn.

Tests work fine in the config screen though.

**Comment by Rouros** [comment]
I did my testing on a local machine running the latest update of Combat ready.

**Comment by Teshynil** [comment]
Hi @Rouros, as the GM you are not show the alerts, only the players can see them, test in a incognito window connected as player if the problem replicates let me know sharing a copy of the console log

**Comment by Rouros** [comment]
yup I connected as a player and didn't see anything. I was running these tests as I was playing with my group and it didn't work for them either. So I set up a test world, logged in as GM in the foundry client and a player in a browser window. Same result.

**Comment by Teshynil** [comment]
Could you share the console log and which modules have active

**Comment by Rouros** [comment]
There are no other modules active.

I found this in the console:

Uncaught (in promise) ReferenceError: Cannot access 'gsap' before initialization
    at NativeAnimation.cleanAnimations (animations.js:266:21)
    at CombatReady.checkForCurrentTurnAnimation (combatReady.js:293:26)
    at CombatReady.toggleCheck (combatReady.js:368:50)
    at Object.fn (combatready.js:76:17)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7854:11)
    at async Game._initializeGameView (foundry.js:8899:5)
    at async Game.initialize (foundry.js:7727:5)

**Comment by Rouros** [comment]
[127.0.0.1-1664631691309.log](https://github.com/Teshynil/combatready/files/9690441/127.0.0.1-1664631691309.log)

**Comment by Rouros** [comment]
I also see this in setup
![Screenshot 2022-10-01 144821](https://user-images.githubusercontent.com/96803351/193412752-8f16a8e6-7eae-40a3-a0a4-3fb6b603d89f.jpg)

**Comment by Teshynil** [comment]
> I also see this in setup
> ![Screenshot 2022-10-01 144821](https://user-images.githubusercontent.com/96803351/193412752-8f16a8e6-7eae-40a3-a0a4-3fb6b603d89f.jpg)
> 

This is because the module is using both v9 and v10 declarations to make it compatible with both

**Comment by Teshynil** [comment]
> [127.0.0.1-1664631691309.log](https://github.com/Teshynil/combatready/files/9690441/127.0.0.1-1664631691309.log)
> 

I will check that

**Comment by sashemi** [comment]
I am NOT replicating this on Foundry 10.291 with DND5e 2.1.5.

NEXT UP and YOUR TURN alerts are indeed showing on screen for the player, as expected.
