### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by CaosFR** [Teshynil/combatready#23]
Hi,

Any chance for a update for the v11 ?

Thanks

**Comment by Teshynil** [comment]
It should be available now, is the 5.0.0 version

**Comment by Fyrexian** [comment]
I dont believe the timer works? Not in PF2e at least. It just stays still (the bar doesn't update) and gives no errors.

**Comment by Teshynil** [comment]
@Fyrexian Could you provide more info?
- FoundryVTT Version
- PF2e Version
- Console Log
- A video would be nice but is not necessary

**Comment by CaosFR** [comment]
> Il devrait être disponible maintenant, est la version 5.0.0

Thanks !

**Comment by Fyrexian** [comment]
> @Fyrexian Could you provide more info?
> 
> * FoundryVTT Version
> * PF2e Version
> * Console Log
> * A video would be nice but is not necessary

v11.307
v5.3.2
No console log to really show
[video.webm](https://github.com/Teshynil/combatready/assets/47077661/4719861e-8d4a-4057-a723-5b0424bed5d6)

**Comment by Teshynil** [comment]
@Fyrexian try un pausing the game

**Comment by Fyrexian** [comment]
Whoops on that, it was unpaused for a different test where it still failed.

The Lightmeter one works, but not the CombatReady one. It still is grayed out like in the video (which is the one I prefer and was testing mainly).

**Comment by Teshynil** [comment]
@Fyrexian it should be now fixed, could you update and check it please

**Comment by Fyrexian** [comment]
Works now, thanks!
